# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "benz-sent-filter"

[build]

[env]
  PYTHONPATH = "/app/src"
  API_PORT = "8002"
  UVICORN_WORKERS = "2"

[processes]
  app = "python -m benz_sent_filter"

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "90s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/health"

[[vm]]
  size = "shared-cpu-1x"
  memory = "2048mb"